[package]
name = "basic-example-script"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
version = "0.0.0"

[dependencies]
basic-example = { path = "../token" }
alloy-primitives.workspace = true
alloy.workspace = true
koba = "0.1.0"
tokio = { version = "1.12.0", features = ["full"] }
