[workspace]
members = ["contracts/token/erc20", "contracts/crypto", "lib/crypto"]

# Explicitly set the resolver to version 2, which is the default for packages with edition >= 2021
# https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html
resolver = "2"


[workspace.package]
edition = "2021"
license = "MIT"
keywords = ["arbitrum", "ethereum", "stylus"]

[profile.release]
codegen-units = 1        
panic = "abort"          
opt-level = "z"          
strip = true             
lto = true               
debug = false            
rpath = false            
debug-assertions = false 
incremental = false      
