[package]
name = "basic-example"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
version = "0.0.0"

[dependencies]
openzeppelin-stylus = { path = "../../../contracts" }
motsu = { git = "https://github.com/openZeppelin/rust-contracts-stylus/", branch = "build/motsu-version" }
alloy-primitives.workspace = true
stylus-sdk.workspace = true
stylus-proc.workspace = true
mini-alloc.workspace = true

[features]
std = []

[lib]
crate-type = ["lib", "cdylib"]
