[package]
# TODO: Figure out public name before v0.1.0 release.
name = "contracts"
categories = ["no-std", "wasm"]
description = "Contracts for Stylus"
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
version = "0.1.0"

[dependencies]
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
stylus-sdk.workspace = true
stylus-proc.workspace = true
mini-alloc.workspace = true
derive_more = "0.99.17"
cfg-if = "1.0"

[dev-dependencies]
grip = { path = "../lib/grip" }
rand = "0.8.5"
once_cell = "1.19.0"

[features]
default = []
tests = []
erc20 = []
erc20_metadata = ["erc20"]
erc721 = []

[lib]
crate-type = ["lib", "cdylib"]
