[package]
name = "erc20-example"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
version = "0.0.0"

[dependencies]
contracts = { path = "../../contracts", features = [
  "erc20_burnable",
  "erc20_capped",
  "erc20_metadata",
  "erc20_pausable",
] }
alloy-primitives.workspace = true
stylus-sdk.workspace = true
stylus-proc.workspace = true
mini-alloc.workspace = true

[dev-dependencies]
e2e = { path = "../../lib/e2e" }
tokio = { version = "1.12.0", features = ["full"] }
eyre = "0.6.8"
alloy = { git = "https://github.com/alloy-rs/alloy", rev = "2bff1dd", features = [
  "contract",
  "network",
  "providers",
  "provider-http",
  "rpc-client",
  "rpc-types-eth",
  "signers",
  "signer-wallet",
  "getrandom",
] }

[features]
default = []
e2e = []

[lib]
crate-type = ["lib", "cdylib"]
