name: e2e-tests
# This workflow runs our end-to-end tests suite.
#
# It roughly follows these steps:
# - A local `nitro-testnode` gets spun up.
# - The test suite runs
# Test contract deployments and test user funding happen per test.
permissions:
  contents: read
on:
  push:
    branches: [ main ]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
jobs:
  e2e-tests:
    name: integration tests suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: cache cargo-stylus
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/.crates.toml
          key: ${{ runner.os }}-cargo-bin-cargo-stylus@0.2.1
          save-always: true

      - name: set up rust
        uses: dtolnay/rust-toolchain@master
        id: toolchain
        with:
          target: wasm32-unknown-unknown
          components: rust-src
          toolchain: nightly-2024-01-01

      - name: install cargo-stylus
        run: RUSTFLAGS="-C link-args=-rdynamic" cargo install cargo-stylus@0.2.1

      - name: setup nitro node
        run: ./e2e-tests/nitro-testnode.sh -d -i

      - name: run integration tests
        run: |
          export NIGHTLY_TOOLCHAIN=${{steps.toolchain.outputs.name}}
          ./e2e-tests/test.sh